USE edu_platform;
SET NAMES utf8mb4;

ALTER TABLE tb_exam ADD COLUMN duration INT NOT NULL DEFAULT 60 COMMENT '考试时长（分钟）' AFTER full_score;

CREATE TABLE IF NOT EXISTS tb_question (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    exam_id BIGINT NOT NULL,
    type TINYINT NOT NULL COMMENT '0=选择题 1=填空题',
    title TEXT NOT NULL COMMENT '题目内容',
    options TEXT COMMENT '选择题选项(JSON数组)',
    answer TEXT COMMENT '正确答案',
    score INT NOT NULL DEFAULT 10,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_exam_id (exam_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='题目表';
