spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration
      - org.springframework.ai.autoconfigure.vectorstore.pgvector.PgVectorStoreAutoConfiguration

  ai:
    openai:
      api-key: ${EDU_AI_DEEPSEEK_API_KEY}
      base-url: ${EDU_AI_DEEPSEEK_BASE_URL:https://api.deepseek.com}

edu:
  ai:
    deepseek:
      api-key: ${EDU_AI_DEEPSEEK_API_KEY}
